name = "MySecondPackage"
uuid = "96febf71-dc66-4e90-9ab0-d578de879c6f"
authors = ["timurUyu <timurUyu@github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
